module.exports = {
  roots: ['<rootDir>/src'],
  collectCoverageFrom: ['<rootDir>/src/**/*.ts'],
  coverageDirectory: 'coverage',
  testEnvironment: 'node',
  transform: {
    '.+\\.ts$': 'ts-jest',
  },
  preset: 'ts-jest',
  verbose: true,
  modulePathIgnorePatterns: ['<rootDir>/dist/'],
  moduleNameMapper: {
    '@/(.*)': '<rootDir>/src',
    '@configs/(.*)': '<rootDir>/src/configs/$1',
    '@helpers/(.*)': '<rootDir>/src/helpers/$1',
    '@controllers/(.*)': '<rootDir>/src/controllers/$1',
    '@routes/(.*)': '<rootDir>/src/routes/$1',
    '@utils/(.*)': '<rootDir>/src/utils/$1',
    '@middlewares/(.*)': '<rootDir>/src/middlewares/$1',
    '@services/(.*)': '<rootDir>/src/services/$1',
    '@dao/(.*)': '<rootDir>/src/dao/$1',
    '@models/(.*)': '<rootDir>/src/models/$1',
    '@validators/(.*)': '<rootDir>/src/validators/$1',
    '@types/(.*)': '<rootDir>/src/types/$1',
    // "/^@controllers\/(.*)$/": "src/controllers/$1.ts"
  },
  setupFiles: ['dotenv/config', '<rootDir>/src/configs/database'],
  globalSetup: '<rootDir>/src/tests/global-setup.ts',
  globalTeardown: '<rootDir>/src/tests/global-teardown.ts',
};
